// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmHw2aEkAqg-xmW91gElNG7pjb7avmepU',
    appId: '1:256244568746:web:4d64ea3630695b920d76d3',
    messagingSenderId: '256244568746',
    projectId: 'courses-b20db',
    authDomain: 'courses-b20db.firebaseapp.com',
    storageBucket: 'courses-b20db.firebasestorage.app',
    measurementId: 'G-0MFVKZL47W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaIYBWk3qvrQbqzm9QbUH_IsKmaHfr8aQ',
    appId: '1:256244568746:android:8d4c9a90318af58e0d76d3',
    messagingSenderId: '256244568746',
    projectId: 'courses-b20db',
    storageBucket: 'courses-b20db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS7elilnwAISYUFDWmRVKyDcy0sgbk4k4',
    appId: '1:256244568746:ios:ddf9833d077f95cb0d76d3',
    messagingSenderId: '256244568746',
    projectId: 'courses-b20db',
    storageBucket: 'courses-b20db.firebasestorage.app',
    iosBundleId: 'com.example.course',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS7elilnwAISYUFDWmRVKyDcy0sgbk4k4',
    appId: '1:256244568746:ios:ddf9833d077f95cb0d76d3',
    messagingSenderId: '256244568746',
    projectId: 'courses-b20db',
    storageBucket: 'courses-b20db.firebasestorage.app',
    iosBundleId: 'com.example.course',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmHw2aEkAqg-xmW91gElNG7pjb7avmepU',
    appId: '1:256244568746:web:80aa211698566ba60d76d3',
    messagingSenderId: '256244568746',
    projectId: 'courses-b20db',
    authDomain: 'courses-b20db.firebaseapp.com',
    storageBucket: 'courses-b20db.firebasestorage.app',
    measurementId: 'G-9W4PMZPYH5',
  );
}
